# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20151127_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('kind', models.IntegerField(choices=[(0, 'Website'), (1, 'App'), (2, 'Map'), (3, 'Facebook')])),
                ('organisation_name', models.CharField(max_length=200)),
                ('categories', models.IntegerField()),
                ('description', models.TextField()),
                ('area_country', models.CharField(max_length=200)),
                ('area_state', models.CharField(max_length=200)),
                ('area_city', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'In Progress')])),
                ('logo', models.FileField(upload_to='uploads/')),
                ('contact_socialmedia', models.URLField()),
                ('contact_telephone', models.CharField(max_length=200)),
                ('contact_address_street', models.CharField(max_length=200)),
                ('contact_address_housenr', models.CharField(max_length=20)),
                ('contact_address_zip', models.CharField(max_length=20)),
                ('contact_address_city', models.CharField(max_length=200)),
                ('contact_address_country', models.CharField(max_length=200)),
                ('languages', models.IntegerField(choices=[(0, 'en')])),
                ('needs', models.CharField(max_length=200)),
                ('programming_language', models.IntegerField(choices=[(0, 'Python')])),
            ],
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
